---
abstract: 'Simple monitoring of applications and services'
author:
  - 'Martin Senger <martin.senger@gmail.com>'
build_requires:
  File::Slurp: 0
  FindBin: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Monitor-Simple
requires:
  Carp: 0
  Data::Dumper: 0
  Fcntl: 0
  File::Basename: 0
  File::Spec: 0
  File::Temp: 0
  Getopt::Long: 2.38
  IO::CaptureOutput: 0
  LWP::UserAgent: 0
  Log::Log4perl: 0
  Parallel::ForkManager: 0
  Pod::Usage: 0
  Time::HiRes: 0
  XML::Simple: 0
  constant: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Monitor-Simple
  homepage: http://search.cpan.org/dist/Monitor-Simple
version: 0.2.4
