--- #YAML:1.0
name:               Monitor-Simple
version:            v0.1.1
abstract:           Simple monitoring of applications and services
author:
    - Martin Senger <martin.senger@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Fcntl:                0
    File::Basename:       0
    File::Spec:           0
    File::Temp:           0
    Getopt::Long:         0
    IO::CaptureOutput:    0
    Log::Log4perl:        0
    LWP::UserAgent:       0
    Parallel::ForkManager:  0
    Pod::Usage:           0
    Test::More:           0
    Time::HiRes:          0
    version:              0.77
    XML::Simple:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
